version: "3.8"
services:
  reauth:
    image: "nathanpb/reauth:0.4.4"
    ports:
      - 6660:6660
    env_file:
      - "reauth/.env"
    volumes:
      - "./reauth/providers.json:/app/providers.json:ro"
      - "./reauth/identity.json:/app/identity.json:ro"
      - "./reauth/scopes.json:/app/scopes.json:ro"
      - "./reauth/managers.json:/app/managers.json:ro"
    depends_on:
      - mongodb
    environment:
      MONGO_CONN_STRING: "mongodb://mongodb"
  mongodb:
    image: "mongo:4.2.10-bionic"
    volumes:
      - "./reauth/entrypoint.js:/docker-entrypoint-initdb.d/entrypoint.js:ro"
